In [177]:
import decode

In [178]:
d = decode.DependencyDecoder()

In [180]:
scores=[[0,1,5,2],
        [1,0,2,3],
        [5,2,0,5],
        [2,3,5,0]]

heads = d.parse_proj(np.array(scores))
[(d,h) for d,h in enumerate(heads)]

[(0, -1), (1, 2), (2, 0), (3, 2)]

In [31]:
import torch

In [38]:
n = np.array([1])
n.shape

(1,)

In [39]:
t = torch.tensor(n)
t.shape

torch.Size([1])

In [41]:
np.transpose(t).shape

torch.Size([1])

In [51]:
type(t)

torch.Tensor

In [52]:
np.shape(t)

torch.Size([1])

In [96]:
t2 = torch.tensor([[0,1,2],
                   [3,0,4],
                   [5,6,0]]).float()

col_zeros = torch.zeros(t2.shape[0]).reshape(-1, 1)
print(col_zeros)
t2_paddedcol = torch.cat([col_zeros,t2],dim=1)
row_zeros = torch.zeros(t2_paddedcol.shape[1]).reshape(1, -1) 
print(row_zeros)
scores = torch.cat([row_zeros,t2_paddedcol],dim=0)

tensor([[0.],
        [0.],
        [0.]])
tensor([[0., 0., 0., 0.]])


In [91]:
scores

tensor([[0., 0., 0., 0.],
        [0., 0., 1., 2.],
        [0., 3., 0., 4.],
        [0., 5., 6., 0.]])

In [86]:
scores[0][0].item()

0.0

In [176]:
x = torch.randn(6, 6)
print(x)
# condition = x < 0.
# print(condition)
row_cond = condition[0]
print(row_cond)
x[row_cond, :][:,row_cond]

tensor([[ 0.4602, -0.8945,  0.2753,  2.3919, -0.7965, -0.8066],
        [-0.5698,  0.2740,  1.0275, -0.8074,  1.5856, -0.2507],
        [ 0.1661, -1.4607,  1.1228,  0.6725, -0.2336, -0.2454],
        [ 0.5129, -0.2115,  0.5313, -0.6744,  0.6948, -0.8970],
        [ 2.6742, -1.0484,  0.6787, -0.6254,  1.1461, -0.9277],
        [-0.7785,  0.6890, -1.2780, -0.7610,  0.4963, -0.4236]])
tensor([ True,  True,  True, False,  True, False])


tensor([[ 0.4602, -0.8945,  0.2753, -0.7965],
        [-0.5698,  0.2740,  1.0275,  1.5856],
        [ 0.1661, -1.4607,  1.1228, -0.2336],
        [ 2.6742, -1.0484,  0.6787,  1.1461]])

In [185]:
heads = [4,7,9]
[(h, d) for h, d in enumerate(heads)] == list(enumerate(heads))

True

In [196]:
indices = [[1,2],[3,4,5],[5]]
for i in indices:
      for j in indices:
        print(i)
        print(j)

[1, 2]
[1, 2]
[1, 2]
[3, 4, 5]
[1, 2]
[5]
[3, 4, 5]
[1, 2]
[3, 4, 5]
[3, 4, 5]
[3, 4, 5]
[5]
[5]
[1, 2]
[5]
[3, 4, 5]
[5]
[5]


In [1]:
def word_index_to_subword_indices(word_index, nested_list):
    '''
    Convert from word index (for nested list of subword tokens),
    to list of subword token indices at that word index
    '''
    if word_index > len(nested_list):
      raise ValueError('word_index exceeds length of nested_list')
    count = 0
    for subword_list in nested_list[:word_index]:
      count += len(subword_list)
    # maybe can do this with functools.reduce
    # count = reduce(lambda x, y: len(x) + len(y),nested_list[:word_index])
    return list(range(count, count+len(nested_list[word_index])))

In [13]:
word_index_to_subword_indices(2, [['▁Odd', 's'], ['▁and'], ['▁End', 's']])

[3, 4]

In [15]:
"""In 1991 , the remains of Russian Tsar Nicholas II and his family
                (except for Alexei and Maria) are discovered .
                The voice of Nicholas 's young son , Tsarevich Alexei Nikolaevich, narrates the
                remainder of the story . 1883 Western Siberia ,
                a young Grigori Rasputin is asked by his father and a group of men to perform magic .
                Rasputin has a vision and denounces one of the men as a horse thief . Although his
                father initially slaps him for making such an accusation , Rasputin watches as the
                man is chased outside and beaten . Twenty years later , Rasputin sees a vision of
                the Virgin Mary , prompting him to become a priest . Rasputin quickly becomes famous,
                 with people , even a bishop , begging for his blessing . """.split()

['In',
 '1991',
 ',',
 'the',
 'remains',
 'of',
 'Russian',
 'Tsar',
 'Nicholas',
 'II',
 'and',
 'his',
 'family',
 '(except',
 'for',
 'Alexei',
 'and',
 'Maria)',
 'are',
 'discovered',
 '.',
 'The',
 'voice',
 'of',
 'Nicholas',
 "'s",
 'young',
 'son',
 ',',
 'Tsarevich',
 'Alexei',
 'Nikolaevich,',
 'narrates',
 'the',
 'remainder',
 'of',
 'the',
 'story',
 '.',
 '1883',
 'Western',
 'Siberia',
 ',',
 'a',
 'young',
 'Grigori',
 'Rasputin',
 'is',
 'asked',
 'by',
 'his',
 'father',
 'and',
 'a',
 'group',
 'of',
 'men',
 'to',
 'perform',
 'magic',
 '.',
 'Rasputin',
 'has',
 'a',
 'vision',
 'and',
 'denounces',
 'one',
 'of',
 'the',
 'men',
 'as',
 'a',
 'horse',
 'thief',
 '.',
 'Although',
 'his',
 'father',
 'initially',
 'slaps',
 'him',
 'for',
 'making',
 'such',
 'an',
 'accusation',
 ',',
 'Rasputin',
 'watches',
 'as',
 'the',
 'man',
 'is',
 'chased',
 'outside',
 'and',
 'beaten',
 '.',
 'Twenty',
 'years',
 'later',
 ',',
 'Rasputin',
 'sees',
 'a',
 'vision',
 